### ISSUE TITLE
Revive the oic feedstock to get new package builds

### ISSUE THREAD

**Issue by wagnerpeer** [conda-forge/oic-feedstock#8]
### Comment:

Hello @mariusvniekerk 
I am addressing you directly, as you are listed as maintainer of this feedstock.
Is there a way to revive this feedstock to get new versions of the `oic` package built and deployed to conda-forge? Reason for my request is the fact, that the only available `oic` package in the conda ecosystem is not Python 3.10 compatible (maybe other lower versions do not work, too).

I have seen, that there are (automatic?) PRs waiting for review. What can we as a community do to get new builds running?

Yours sincerely

**Comment by wagnerpeer** [comment]
Hey @beckermr 
Maybe you can help?

**Comment by beckermr** [comment]
Feel free to add yourself as a maintainer using the admin command in our docs. I will merge that and you can be on your way! Thanks a bunch for taking this over!

**Comment by wagnerpeer** [comment]
Does it go in the title, or in a comment?
@conda-forge-admin, please add user @wagnerpeer

**Comment by wagnerpeer** [comment]
Hey @beckermr
There it is...
Thank you for helping.

**Comment by beckermr** [comment]
Done. Have fun!
